title: Карло Иван - Автоматизация на 1С
description: Эксперт с опытом в автоматизации бизнес-процессов на платформе 1С
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
